##### Menu
menu:
  主页: /
  归档: /archives
  关于: /about


#### Widgets
widgets:
- weibo
- archive
- category
- tag
- links
- rss

## provide seven widgets:category,tag,rss,,archivetagcloud,links,weibo,douban


#### RSS
rss: /atom.xml

#### Image
imglogo:
  enable: true
  src: img/logo.png
favicon: img/favicon.ico   ## size:32px*32px
author_img: img/author.jpg ## size:220px*220px

### Theme Color
theme_color:
    theme: '#2ca6cb'    ##the defaut theme color is blue

# 代码高亮主题
# available: default | night
highlight_theme: night

#### index post is expanding or not
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More

close_aside: false  # close sidebar in post page if true
mathjax: false      # enable mathjax if true

### Creative Commons License Support, see http://creativecommons.org/
### you can choose: by , by-nc , by-nc-nd , by-nc-sa , by-nd , by-sa , zero
creative_commons: by-nc-nd

#### Author information
author:
  intro_line1: "Hello, I'm Qianmo."
  intro_line2: "This is my blog, believe it or not."
  weibo: toqianmo
  weibo_verifier: 43ce7f75
  tsina: 1702810323
  zhihu: qian-mo-32-16
  email: root@0xffffff.org
  twitter: hurleyhades
  github: hurley25
  facebook: hurleyhades
  linkedin:
  google_plus:
  stackoverflow:

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.

#### Links
links:
  Dutor: http://www.dutor.net/
  Jeff Preshing: http://preshing.com/
  丰茂: http://my.oschina.net/tfengmao/blog
  任立翔: http://glacierlx.sinaapp.com/
  刘永康: http://liuyongkang.org
  叔度: http://blog.zhuzhaoyuan.com/
  吴子旋: http://blog.wuzx.me/
  孔建军: http://amosk.info/blog/
  宋润雨: http://blog.csdn.net/u011438608
  崔姣姣: http://blog.csdn.net/cuijiaojiaofendou
  常宫小戎: http://blog.csdn.net/u011056004
  李力: http://tioo.sinaapp.com
  李国婷: http://blog.sina.com.cn/lgtlgtlgt
  李通: http://windleaves.blog.163.com/
  杜斌: http://blog.db89.org
  杜炳阳: http://drock.sinaapp.com/
  杨帆: http://blog.163.com/yangfan876@126/
  林达意: http://heylindayi.sinaapp.com/
  武特: http://edsionte.com/
  汤秋媛: http://blog.sina.com.cn/t123tarry
  沈昭萌: http://blog.csdn.net/xianszm007
  淘宝搜索技术: http://www.searchtb.com/
  王亚刚老师: http://blog.csdn.net/lazy_linux
  王聪: http://wangcong.org/
  石松: http://loveshisong.cn/
  程序员和小女生: http://hzzz.lengzzz.com/blog/
  酷壳: http://coolshell.cn/
  阿里核心系统: http://csrd.aliapp.com
  陈嘉杰: http://nonodevil.com/
  陈莉君老师: http://home.lupaworld.com/space-uid-26540.html
  霸爷: http://blog.yufeng.info/
  高源: http://alinuxer.net
  黄方直: http://www.1anc3r.me/
  李林翰: http://www.lewin.org.cn/


#### Comment
duoshuo_shortname: qianmo
#disqus_shortname:

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID.
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: false
  id:        ## e.g. UA-46321946-2 your google analytics ID.
  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.

## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: false
  sitecode: 

cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
google_cse:
  enable: false
  cx:   ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search
## title: search
## ---

baidu_search:     ## http://zn.baidu.com/
  enable: false
  id: 4310368124779342010
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site


tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
